# This rule is not used by the project kubernetes-controller-interview itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to notifications.aymenkoched resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubernetes-controller-interview
    app.kubernetes.io/managed-by: kustomize
  name: slackmessage-viewer-role
rules:
- apiGroups:
  - notifications.aymenkoched
  resources:
  - slackmessages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - notifications.aymenkoched
  resources:
  - slackmessages/status
  verbs:
  - get
